### ISSUE TITLE
Camera not releasing

### ISSUE THREAD

**Issue by docPhil99** [jbhunt/parallel-pyspin#3]
Hi,
Thanks for providing this code. It's a lot nicer to use than the official examples! I'm running this on Linux Mint 20.2, python 3.8.10 and have an issue with the camera not been released. I've got a minimal example code. This was run after a reboot.
```
cam1 = primary.PrimaryCamera(serial_number=21293195)
cam1.prime('test1.mp4', backend='Spinnaker')
cam1.trigger()
time.sleep(5)
cam1.stop()
cam1.release()
```
This records okay but throws an exception 
```
Process PrimaryCameraChildProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/phil/python/spin/parallel-pyspin/llpyspin/processes.py", line 163, in run
    _cleanup(system, cameras, pointer)
  File "/home/phil/python/spin/parallel-pyspin/llpyspin/processes.py", line 55, in _cleanup
    system.ReleaseInstance()
  File "/home/phil/.virtualenvs/spin/lib/python3.8/site-packages/PySpin.py", line 35703, in ReleaseInstance
    return _PySpin._SWIG_SysPtr_ReleaseInstance(self)
_PySpin.SpinnakerException: Spinnaker: Can't clear a camera because something still holds a reference to the camera [-1004]
terminate called after throwing an instance of 'Spinnaker::Exception'
  what():  Spinnaker: Can't clear a camera because something still holds a reference to the camera [-1004]
```
Also if I have two cameras, not hardware linked, can I use two instances of PrimaryCamera? Again this records both but each process throw the same exception.

**Comment by jbhunt** [comment]
Hello @docPhil99,

Sorry I just saw this issue. The problem is with the `_cleanup` function in the `processes.py` module. I tried writing a reusable function for removing references to the camera pointer objects; however, passing the pointers to the function creates a new reference to these objects which is why you get this error. I pushed a patch that removes this function and handles the clean up in the same context as where the pointers are instantiated. Please pull these changes to your local repo and try this again. If you still get an error, please let me know.

Also, to answer your question, if you are using two cameras not synchronized by a hardware trigger, you can just use two instances of a PrimaryCamera class.

I would also pass absolute file paths to the `prime` method. I think it will go ahead and create the video containers in the working directory if you just pass the file name without prefixing the path, but I never actually tested this.

Josh

**Comment by docPhil99** [comment]
I thought must be something to do with that. This works perfect, thanks. It does save in the working directory without the full file path.
